### ISSUE TITLE
Plastico para evitar dolor de ojos

### ISSUE THREAD

**Issue by madelgj** [asrob-uc3m/contador-de-accidentes#1]
Necesitamos poner algo encima de los Leds para que se puedan ver los numeros, pero sin q t duelan los ojos.

**Comment by Siotma** [comment]
Soy muy fan del título de esta issue XD

Una buena solución para evitar que los leds brillen demasiado es la modulación PWM del brillo, algo que se puede hacer por software.

**Comment by JorFru** [comment]
Por software es demasiado fácil hacerlo. Además de atenuar, supongo que se pretende suavizar los píxeles para que parezcan segmentos.
Decidme las dimensiones aproximadas de la plancha. Igual se puede imprimir algo. Tengo una idea.

**Comment by madelgj** [comment]
Lo intentamos hacer por software, pero no conseguíamos que se viesen bien los números.
@wenflehecanario propuso poner unos folios encima (funcionó) y más adelante añadirle un marco y una placa poniendo que es un contador de días sin accidentes.

**Comment by David-Estevez** [comment]
A mi la solución de los folios me gusta, es sencilla y queda francamente bien. Se podría incluso imprimir en un A3 lo de "Días sin accidentes" y usar eso como difusor en lugar de folios en blanco. Así tendríamos un 2 en 1, contador y cartel.

**Comment by jgvictores** [comment]
> Lo intentamos hacer por software, pero no conseguíamos que se viesen bien los números.

Suponiendo que PWM causa parpadeos incómodos o algo, ¿atenuar el efecto mediante electrónica (p.ej. RC)?

**Comment by David-Estevez** [comment]
> Suponiendo que PWM causa parpadeos incómodos o algo, ¿atenuar el efecto mediante electrónica (p.ej. RC)?

Los LEDs traen ya su electrónica de potencia y control incorporada en el encapsulado.

 La razón de que no se viesen bien los números es porque los números están formados de varios puntitos (LEDs) haciendo de los distintos segmentos del display. Sin un recubrimento adicional, se ven todos los LEDs (encendidos y apagados) y cuesta distinguir bien los segmentos encendidos de los apagados. Al cubrirlos todos con un papel, ya sólo se ven los encendidos, lo cual ayuda al cerebro a interpretar los puntitos como números.

**Comment by David-Estevez** [comment]
Dejo por aquí un ejemplo de la solución actual que hizo @wenflehecanario 

![image](https://user-images.githubusercontent.com/1451819/41685157-e3e1b708-74df-11e8-898f-54c9780b2369.png)

Conociéndonos, es probable que se siga la filosofía del "si funciona, no lo toques" y no se llegue nunca a actualizar. :sweat_smile:
