### ISSUE TITLE
Typo en el número 9

### ISSUE THREAD

**Issue by L4g0** [asrob-uc3m/contador-de-accidentes#11]
Falta el segmento de abajo del 9

![image](https://user-images.githubusercontent.com/23212123/66438353-b35a2200-ea2c-11e9-9a71-e2740538b219.png)

![image](https://user-images.githubusercontent.com/23212123/66438399-d684d180-ea2c-11e9-8cef-b0382d45fb90.png)

**Comment by David-Estevez** [comment]
BLUE.

**Comment by JorFru** [comment]
![photo_2019-10-19_21-19-24](https://user-images.githubusercontent.com/11017088/67150316-380f3080-f2b6-11e9-9500-8d4d3c5f01e5.jpg)
Corregido en https://github.com/asrob-uc3m/contador-de-accidentes/commit/c0cd795b9f59f152625544a956d83a3079df429d
