### ISSUE TITLE
El contador siempre cuenta 1 al inicio

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/contador-de-accidentes#2]
Al arrancar, el contador siempre pasa de 0 a 1 en un segundo. Si se acciona el pulsador, vuelve a 0 y funciona correctamente (no se incrementa hasta el día siguiente).

**Comment by jorgercobo** [comment]
Es una buena practica enlazar el commit en el que soluciona el problema por trazabilidad y explicar cual era el problema :smile:
