### ISSUE TITLE
Diseñar e imprimir caja para la electronica

### ISSUE THREAD

**Issue by DiegoGarciaX2** [asrob-uc3m/contador-de-accidentes#5]
Esta caja se situaria detras del panel de madera.

**Comment by DAG00DAG33** [comment]
[Caja contador.zip](https://github.com/asrob-uc3m/contador-de-accidentes/files/2498358/Caja.contador.zip)

No sabia donde subirlo, lo dejo aquí

**Comment by DiegoGarciaX2** [comment]
me gusta, pero se me ha ocurrido algo que podemos modificar, trae el portatil el proximo dia si puedes

**Comment by DAG00DAG33** [comment]
[caja contador v3.zip](https://github.com/asrob-uc3m/contador-de-accidentes/files/2519223/caja.contador.v3.zip)

**Comment by jgvictores** [comment]
> No sabia donde subirlo, lo dejo aquí

Te recomiendo un par de tutoriales!
- https://github.com/asrob-uc3m/tutoriales/blob/master/software/version-control/git.md
- https://david-estevez.gitbooks.io/the-git-the-bad-and-the-ugly/content/es/

**Comment by DiegoGarciaX2** [comment]
La imprimiré y traere para el proximo dia.
PS: si tienes tiempo mira los tutoriales que te ha pasado Juan
